### ISSUE TITLE
anihub.tv

### ISSUE THREAD

**Issue by ghost** [LiCybora/NanoDefenderFirefox#195]
### Explain what was not right (optional if obvious):

nano defender isnt protecting ublock origin in this site

### Reproduction steps (optional if trivial):

just enter in the website and try to watch something

### Environment (Required):

- Operating System and Version: Win10
- Browser and Version: Firefox last version
- Adblocker and Version: Ublock Origin
- Nano Defender Version: 15.0.0.205

**Comment by mapx-** [comment]
fixed, update `uBlock filters`

**Comment by ghost** [comment]
> 
> 
> fixed, update `uBlock filters`

Hello, I cleared the cache in filter list and updated, tried again and its still appearing

**Comment by mapx-** [comment]
Do you see in the logger any of these filters

```
*$script,redirect-rule=noopjs,domain=anihub.tv
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=anihub.tv
```

eventually close / reopen FF and force update again all the lists

**Comment by ghost** [comment]
> 
> 
> Do you see in the logger any of these filters
> 
> ```
> *$script,redirect-rule=noopjs,domain=anihub.tv
> @@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=anihub.tv
> ```
> 
> eventually close / reopen FF and force update again all the lists

it's there but still dont working

**Comment by mapx-** [comment]
- tested again in firefox, working fine on my end. 
- disable all other addons, keep enabled only uBO and test again

**Comment by ghost** [comment]
ok now its fine, thank you a lot!!!!
